### PR TITLE
Feature/multi root workspace

### PR DESCRIPTION
**Pull request by BenWildeman**
* Show Workspace Folder Picker if mult-root when creating terminal
* Support Workspace Folder Name in directory field of defaultTerminals
* Resolve relative paths for directory field of default terminals for both mutli-root and non multi-root workspaces

### CODE REVIEW

**Comment by BenWildeman** [comment]
fixes #11

**Comment by kazelone** [comment]
@BenWildeman Works well. Only thing is that default terminals without commands are "blank" when first opened and need any input to actually show. This can be "fixed" by sending a blank command after creation : 
```ts
if (command) {
    _terminal.sendCommand(command, executeCommand);
} else {
    _terminal.sendCommand('');
}
```
in common -> loadTerminals

**Comment by BenWildeman** [comment]
> @BenWildeman Works well. Only thing is that default terminals without commands are "blank" when first opened and need any input to actually show. This can be "fixed" by sending a blank command after creation :
> 
> ```ts
> if (command) {
>     _terminal.sendCommand(command, executeCommand);
> } else {
>     _terminal.sendCommand('');
> }
> ```
> 
> in common -> loadTerminals

This is a bug with VS Code itself, and seems to depend on which terminal you use. for instance, I use powershell v6 and it doesn't do this (regular powershell it does). however, I will add this as a setting instead of just assuming it's required for everyone :)

**Comment by BenWildeman** [comment]
just looked into the issue above, it's a windows 10 specific issue that was fixed and landed in windows build 1903 so I will not be adding in a feature to circumvent this

reference: https://github.com/microsoft/vscode/issues/57803#issuecomment-449495423

(I updated to powershell v6 around the same time of updating windows, hence why I thought it was a specific terminal issue)

**Comment by kazelone** [comment]
Well, the update still haven't landed on LTSC, but it's not the end of the world and I can just use a default command of "ps" or "ls" or something in the meantime.

**Pull request merged**
