### PR TITLE
Patch/default terminal path resolution

### PR DESCRIPTION
**Pull request by kazelone**
Implemented a more robust and flexible way of specifying the cwd of default terminals, since I had issue with those in a multi-root workspace configuration.

### CODE REVIEW

**Comment by BenWildeman** [comment]
I've tested this. personally, I use relative paths within my defaultTerminals, but with your change, this breaks 
image

**Comment by kazelone** [comment]
> 
> 
> I've tested this. personally, I use relative paths within my defaultTerminals, but with your change, this breaks
> image

Are you using a workspace or just an opened folder?
Also what's the path of the folder vs the directory in your default terminal?
I assume you have a project opened at `c:\code\work` and the directory is `directory: "packages\pz-api"`?

**Comment by BenWildeman** [comment]
I see what you're trying to accomplish. mind if I take this over and make it more robust?

**Comment by kazelone** [comment]
I have no objection.
I just wanted to fix the issue with multi-root workspace (you can't use relative path with the current implementation, because it's relative to... something, which is undeterministic (sometime it starts from the directory in which your workplace is, sometime the first workspace folder...))

**Comment by BenWildeman** [comment]
@kazelone would you like to take a look at #9 and see if this is sufficient

**Comment by kazelone** [comment]
@BenWildeman Works well. Only thing is that default terminals without commands are "blank" when first opened and need any input to actually show. This can be "fixed" by sending a blank command after creation : 
```ts
if (command) {
    _terminal.sendCommand(command, executeCommand);
} else {
    _terminal.sendCommand('');
}
```
in common -> loadTerminals

**Comment by kazelone** [comment]
@BenWildeman Done, I commented there.

**Pull request closed without merging**
